// Core types for the mini-game arcade.
// Shared between client and server: the server treats the catalog as the
// source of truth for prices, levels and age gating.

/**
 * Engine identifiers. Each value maps to a React component in
 * client/src/minigames/games/registry/gameRegistry.ts.
 * To add a brand-new engine: build the component, register it there,
 * and add its id here.
 */
export type GameEngineType =
  | "quiz"
  | "memory"
  | "puzzle"
  | "dragdrop"
  | "tappop"
  | "sequence"
  | "mathrunner"
  | "wordbuilder"
  | "logicgrid"
  | "citybuilder"
  | "codinglite"
  | "finance"
  | "jigsaw"
  | "pattern"
  | "maze"
  | "spotdiff"
  | "sudoku"
  | "watertracker"
  | "sleepguardian"
  | "breathing";

export type AgeGroup = "3-5" | "6-8" | "9-12";
export type GameDifficulty = "easy" | "medium" | "hard";
export type GameCategory = "preschool" | "elementary" | "preteen" | "puzzle" | "wellness";

/** Monetization tier. `free` games need no subscription; `premium` games are
 *  unlocked by an active family subscription (the conversion driver). */
export type GameTier = "free" | "premium";

export interface GameThemeColors {
  primary: string;
  secondary: string;
  background: string;
  accent: string;
}

/**
 * One playable difficulty level of a game. Games can have any number of
 * levels; level 1 is always included with the purchase, higher levels are
 * unlocked in order with reward points.
 */
export interface GameLevel {
  /** 1-based, sequential */
  level: number;
  /** Optional display name, e.g. "Speed Round" */
  name?: string;
  difficulty: GameDifficulty;
  /** Score scale for a perfect run at this level */
  rewardPoints: number;
  /** Seconds per round; omit for untimed games */
  timeLimit?: number;
  /** Reward points to unlock; 0 for level 1 (included with purchase) */
  unlockCost: number;
  /** Extra engine config merged over the game's base initialData */
  initialData?: Record<string, unknown>;
}

export interface GameDefinition {
  /** Stable unique id — referenced by DB rows, never change once shipped */
  id: string;
  engine: GameEngineType;
  title: string;
  description: string;
  ageGroup: AgeGroup;
  /** Nominal difficulty shown in the catalog; levels can escalate beyond it */
  difficulty: GameDifficulty;
  category: GameCategory;
  icon: string;
  themeColors: GameThemeColors;
  /** Base score scale (level 1) */
  rewardPoints: number;
  /** Reward points needed to buy the game (parent approval required) */
  purchaseCost: number;
  /** Base seconds per round; levels tighten it */
  timeLimit?: number;
  /** Base engine config (variant selection etc.) */
  initialData?: Record<string, unknown>;
  /** Playable levels, ascending. Generated by defineGame unless customized. */
  levels: GameLevel[];
  /** Monetization tier (assigned centrally in tiers.ts; defaults to premium). */
  tier?: GameTier;
  /** The single cross-age "hero" game, shown to every age group as the free hook. */
  flagship?: boolean;
}

/**
 * Author-facing spec: everything in GameDefinition except `levels`,
 * plus an optional level customization (see defineGame in levels.ts).
 */
export interface GameSpec extends Omit<GameDefinition, "levels"> {
  /**
   * - omitted        → 3 standard levels
   * - number         → that many standard levels
   * - array of specs → one entry per level; fields you set override the
   *                    standard progression for that level
   */
  levels?: number | Array<Partial<Omit<GameLevel, "level">>>;
}
