// Ages 6-8 (Elementary) games.
// To add a game to this category, add one defineGame() entry here.

import { defineGame } from "../levels";
import type { GameDefinition } from "../types";

export const elementaryGames: GameDefinition[] = [
  defineGame({
    id: "math-runner",
    engine: "mathrunner",
    title: "Math Hero Dash",
    description: "Solve math problems to keep your hero running!",
    ageGroup: "6-8",
    difficulty: "medium",
    category: "elementary",
    icon: "➕",
    rewardPoints: 100,
    purchaseCost: 60,
    timeLimit: 120,
    themeColors: { primary: "#1565C0", secondary: "#BBDEFB", background: "#E3F2FD", accent: "#2196F3" },
  }),
  defineGame({
    id: "word-builder",
    engine: "wordbuilder",
    title: "Word Builder Blocks",
    description: "Build words from letter blocks before time runs out!",
    ageGroup: "6-8",
    difficulty: "medium",
    category: "elementary",
    icon: "📝",
    rewardPoints: 100,
    purchaseCost: 60,
    timeLimit: 120,
    themeColors: { primary: "#6A1B9A", secondary: "#E1BEE7", background: "#F3E5F5", accent: "#9C27B0" },
  }),
  defineGame({
    id: "memory-flip",
    engine: "memory",
    title: "Memory Flip Quest",
    description: "Flip the cards and find all the matching pairs!",
    ageGroup: "6-8",
    difficulty: "medium",
    category: "elementary",
    icon: "🃏",
    rewardPoints: 100,
    purchaseCost: 60,
    timeLimit: 120,
    themeColors: { primary: "#00695C", secondary: "#B2DFDB", background: "#E0F2F1", accent: "#009688" },
  }),
  defineGame({
    id: "hygiene-hero",
    engine: "sequence",
    title: "Hygiene Hero",
    description: "Put the healthy hygiene steps in the right order!",
    ageGroup: "6-8",
    difficulty: "easy",
    category: "elementary",
    icon: "🪥",
    rewardPoints: 80,
    purchaseCost: 50,
    themeColors: { primary: "#0288D1", secondary: "#B3E5FC", background: "#E1F5FE", accent: "#03A9F4" },
  }),
  defineGame({
    id: "quiz-spinner",
    engine: "quiz",
    title: "Quiz Spinner",
    description: "Spin the wheel and answer fun trivia questions!",
    ageGroup: "6-8",
    difficulty: "medium",
    category: "elementary",
    icon: "🎡",
    rewardPoints: 100,
    purchaseCost: 60,
    timeLimit: 90,
    themeColors: { primary: "#F57C00", secondary: "#FFE0B2", background: "#FFF8E1", accent: "#FF9800" },
    initialData: { variant: "spinner" },
  }),
];
