// Ages 3-5 (Preschool) games.
// To add a game to this category, add one defineGame() entry here.

import { defineGame } from "../levels";
import type { GameDefinition } from "../types";

export const preschoolGames: GameDefinition[] = [
  defineGame({
    id: "shape-match",
    engine: "dragdrop",
    title: "Shape Match Adventure",
    description: "Drag each shape into its matching home!",
    ageGroup: "3-5",
    difficulty: "easy",
    category: "preschool",
    icon: "🔷",
    rewardPoints: 50,
    purchaseCost: 40,
    timeLimit: 90,
    themeColors: { primary: "#FF7043", secondary: "#FFE0B2", background: "#FFF3E0", accent: "#FF9800" },
    initialData: { variant: "shapes" },
  }),
  defineGame({
    id: "color-pop",
    engine: "tappop",
    title: "Color Pop Balloons",
    description: "Pop only the balloons with the right color!",
    ageGroup: "3-5",
    difficulty: "easy",
    category: "preschool",
    icon: "🎈",
    rewardPoints: 60,
    purchaseCost: 40,
    timeLimit: 60,
    themeColors: { primary: "#E91E63", secondary: "#FCE4EC", background: "#FFF0F5", accent: "#FF4081" },
  }),
  defineGame({
    id: "animal-sound-quiz",
    engine: "quiz",
    title: "Animal Sound Quiz",
    description: "Which animal makes that sound? Take a guess!",
    ageGroup: "3-5",
    difficulty: "easy",
    category: "preschool",
    icon: "🦁",
    rewardPoints: 50,
    purchaseCost: 40,
    timeLimit: 60,
    themeColors: { primary: "#8BC34A", secondary: "#DCEDC8", background: "#F1F8E9", accent: "#4CAF50" },
    initialData: { variant: "sound" },
  }),
  defineGame({
    id: "emotion-faces",
    engine: "dragdrop",
    title: "Emotion Faces",
    description: "Match the feelings to the friendly faces!",
    ageGroup: "3-5",
    difficulty: "easy",
    category: "preschool",
    icon: "😊",
    rewardPoints: 50,
    purchaseCost: 40,
    themeColors: { primary: "#FF9800", secondary: "#FFE0B2", background: "#FFFDE7", accent: "#FFC107" },
    initialData: { variant: "emotions" },
  }),
  defineGame({
    id: "healthy-plate",
    engine: "dragdrop",
    title: "Healthy Plate Builder",
    description: "Build a yummy, healthy plate of food!",
    ageGroup: "3-5",
    difficulty: "easy",
    category: "preschool",
    icon: "🥗",
    rewardPoints: 60,
    purchaseCost: 45,
    themeColors: { primary: "#4CAF50", secondary: "#C8E6C9", background: "#F1F8E9", accent: "#66BB6A" },
    initialData: { variant: "healthyplate" },
  }),
];
