// Ages 9-12 (Pre-Teen) games.
// To add a game to this category, add one defineGame() entry here.

import { defineGame } from "../levels";
import type { GameDefinition } from "../types";

export const preteenGames: GameDefinition[] = [
  defineGame({
    id: "logic-grid",
    engine: "logicgrid",
    title: "Logic Grid Puzzle",
    description: "Use clues and deduction to crack the logic grid!",
    ageGroup: "9-12",
    difficulty: "hard",
    category: "preteen",
    icon: "🔎",
    rewardPoints: 150,
    purchaseCost: 80,
    timeLimit: 300,
    themeColors: { primary: "#37474F", secondary: "#CFD8DC", background: "#ECEFF1", accent: "#607D8B" },
  }),
  defineGame({
    id: "eco-city",
    engine: "citybuilder",
    title: "Eco City Builder",
    description: "Build a green city and keep your citizens happy!",
    ageGroup: "9-12",
    difficulty: "medium",
    category: "preteen",
    icon: "🏙️",
    rewardPoints: 120,
    purchaseCost: 70,
    themeColors: { primary: "#2E7D32", secondary: "#C8E6C9", background: "#F1F8E9", accent: "#43A047" },
  }),
  defineGame({
    id: "coding-maze",
    engine: "codinglite",
    title: "Coding Lite Maze",
    description: "Program your robot with commands to escape the maze!",
    ageGroup: "9-12",
    difficulty: "medium",
    category: "preteen",
    icon: "💻",
    rewardPoints: 150,
    purchaseCost: 80,
    themeColors: { primary: "#1A237E", secondary: "#C5CAE9", background: "#E8EAF6", accent: "#3F51B5" },
  }),
  defineGame({
    id: "finance-fun",
    engine: "finance",
    title: "Finance Fun",
    description: "Learn to save, spend and budget like a money hero!",
    ageGroup: "9-12",
    difficulty: "medium",
    category: "preteen",
    icon: "💰",
    rewardPoints: 120,
    purchaseCost: 70,
    themeColors: { primary: "#E65100", secondary: "#FFE0B2", background: "#FFF3E0", accent: "#FF6D00" },
  }),
  defineGame({
    id: "trivia-battle",
    engine: "quiz",
    title: "Trivia Battle",
    description: "Race the clock in a rapid-fire trivia battle!",
    ageGroup: "9-12",
    difficulty: "hard",
    category: "preteen",
    icon: "🏆",
    rewardPoints: 150,
    purchaseCost: 80,
    timeLimit: 60,
    themeColors: { primary: "#880E4F", secondary: "#F8BBD9", background: "#FCE4EC", accent: "#E91E63" },
    initialData: { variant: "battle" },
  }),
];
