// Puzzle games (mixed ages).
// To add a game to this category, add one defineGame() entry here.

import { defineGame } from "../levels";
import type { GameDefinition } from "../types";

export const puzzleGames: GameDefinition[] = [
  defineGame({
    id: "jigsaw",
    engine: "jigsaw",
    title: "Jigsaw World",
    description: "Piece together colorful jigsaw puzzles!",
    ageGroup: "6-8",
    difficulty: "medium",
    category: "puzzle",
    icon: "🧩",
    rewardPoints: 120,
    purchaseCost: 65,
    themeColors: { primary: "#AD1457", secondary: "#F8BBD9", background: "#FCE4EC", accent: "#E91E63" },
  }),
  defineGame({
    id: "pattern-unlock",
    engine: "pattern",
    title: "Pattern Unlock",
    description: "Watch, remember, and repeat the secret pattern!",
    ageGroup: "6-8",
    difficulty: "medium",
    category: "puzzle",
    icon: "🔮",
    rewardPoints: 100,
    purchaseCost: 60,
    timeLimit: 120,
    themeColors: { primary: "#4527A0", secondary: "#D1C4E9", background: "#EDE7F6", accent: "#673AB7" },
  }),
  defineGame({
    id: "maze-escape",
    engine: "maze",
    title: "Maze Escape",
    description: "Find your way through twisting mazes to freedom!",
    ageGroup: "6-8",
    difficulty: "medium",
    category: "puzzle",
    icon: "🌀",
    rewardPoints: 100,
    purchaseCost: 60,
    themeColors: { primary: "#006064", secondary: "#B2EBF2", background: "#E0F7FA", accent: "#00BCD4" },
  }),
  defineGame({
    id: "spot-diff",
    engine: "spotdiff",
    title: "Spot the Difference",
    description: "Find all the sneaky differences between two pictures!",
    ageGroup: "6-8",
    difficulty: "medium",
    category: "puzzle",
    icon: "🔍",
    rewardPoints: 100,
    purchaseCost: 60,
    timeLimit: 120,
    themeColors: { primary: "#1B5E20", secondary: "#C8E6C9", background: "#F1F8E9", accent: "#4CAF50" },
  }),
  defineGame({
    id: "sudoku",
    engine: "sudoku",
    title: "Sudoku Junior",
    description: "Fill the grid so every row and box adds up!",
    ageGroup: "9-12",
    difficulty: "hard",
    category: "puzzle",
    icon: "🔢",
    rewardPoints: 150,
    purchaseCost: 80,
    timeLimit: 300,
    themeColors: { primary: "#1A237E", secondary: "#C5CAE9", background: "#E8EAF6", accent: "#5C6BC0" },
  }),
];
